name: idr0099
channels:
  - defaults
  - ome
  - manics
dependencies:
  - bftools=6.5.1
  - bioformats2raw=0.2.6
  - jupyterlab=2.2.6
  - numpy=1.19.2
  - omero-py=5.8.2
  - openjdk=11.0.6
  - pandas=1.1.3
  - pip=20.2.4
  - scipy
  - tifffile=2020.10.1
