name: idr0099
channels:
  - ome
  - manics
  - defaults
dependencies:
  - bftools=6.5.1
  - bioformats2raw=0.2.6
  - imageio=2.9.0
  - jupyterlab=2.2.6
  - matplotlib=3.3.2
  - nodejs=10.13.0
  - numpy=1.19.2
  - omero-py=5.8.2
  - openjdk=8.0.152
  - pandas=1.1.3
  - pip=20.2.4
  - python=3.8.5
  - requests=2.24.0
  - scipy=1.5.2
  - tifffile=2020.10.1
  - pip:
    - omero-metadata==0.6.0
