---
name: idr0099-jain-beetlelightsheet/experimentA
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes

  - name: Reporter
    include: yes

  - name: Experimental Condition [Transgenic Line]
    clientname: Transgenic Line
    include: yes

  - name: Experimental Condition [Genotype]
    clientname: Genotype
    include: yes

  - name: Experimental Condition [Time Interval]
    clientname: Time Interval
    include: yes

  - name: Experimental Condition [Labelled Cellular Structure]
    clientname: Labelled Cellular Structure
    include: yes

  - name: Views Imaged for Multiview Reconstruction
    include: yes

  - name: Voxel Dimensions
    include: yes

  - name: Comment [Image File]
    clientname: Image File Comment
    include: yes

  - name: Processed Data File
    include: yes



  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

advanced:
  well_to_images: true
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
